#
# use stuff
#

resources:

  #
  # we'll be working off a particular repository and branch
  #

  - name: "repo-pull"
    type: "git"
    source:
      uri: {{repo-dev-uri}}
      branch: {{repo-dev-branch}}

  - name: "repo-push"
    type: "git"
    source:
      uri: {{repo-dev-uri}}
      branch: {{repo-dev-branch}}

#
# do stuff
#

jobs:

  #
  # create a dev release for ourselves
  #

  - name: "create-release"
    public: true
    plan:
      - aggregate:
          - get: "repo"
            trigger: true
          - get: "version"
            params:
              pre: "dev"
      - task: "create-release"
        file: "repo/ci/tasks/create-release/task.yml"
      - put: "version"
        params:
          file: "version/number"
      - put: "release"
        params:
          from: "repo/dev_releases/logsearch/logsearch-(.+).tgz"
          to: "dev_releases/"
