#!/bin/bash

set -e
set -u

# args: {number}

cd $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

mkdir -p ../../config/pr

PR_NUMBER="$1"

PR_GITHUB=$( wget -qO- "https://api.github.com/repos/$PR_REPO_OWNER/$PR_REPO_NAME/pulls/$PR_NUMBER" )

PR_BASE_REF=$( echo "${PR_GITHUB}" | jq -r '.base.ref' )

PR_HEAD_OWNER=$( echo "${PR_GITHUB}" | jq -r '.head.repo.owner.login' )
PR_HEAD_NAME=$( echo "${PR_GITHUB}" | jq -r '.head.repo.name' )
PR_HEAD_REF=$( echo "${PR_GITHUB}" | jq -r '.head.ref' )

echo "jobs:"
cat ../dev/jobs-tests.yml | sed 's/^/  /'
cat jobs.yml | sed 's/^/  /'

echo "resources:"
cat ../dev/resources.yml | sed 's/^/  /'
cat resources.yml | sed 's/^/  /'

cat > ../../config/pr/$1.yml << EOF
repo-branch: "${PR_BASE_REF}"
repo-pr-uri: "https://github.com/${PR_HEAD_OWNER}/${PR_HEAD_NAME}.git"
repo-pr-branch: "${PR_HEAD_REF}"
release-prefix: "pr/"
bosh-lite-e2e-deployment: "develop-e2e"
EOF
