repo-uri: "https://github.com/dpb587/logsearch-boshrelease.git"

artifact-bucket: "logsearch-boshrelease-concoursetest"

git-private-key: ~

github-user: "dpb587"
github-repository: "logsearch-boshrelease"
github-api-token: ~

aws-access-key: ~
aws-secret-key: ~

bosh-lite-username: "admin"
bosh-lite-password: "admin"
