repo-uri: "git@github.com:dpb587/logsearch-boshrelease.git"
repo-key: ~

artifact-bucket: "logsearch-boshrelease-concoursetest"

github-user: "dpb587"
github-repository: "logsearch-boshrelease"
github-api-token: ~

aws-access-key: ~
aws-secret-key: ~

bosh-lite-username: "admin"
bosh-lite-password: "admin"
