repo-uri: "https://github.com/dpb587/logsearch-boshrelease.git"
repo-branch: "develop"

release-bucket: "logsearch-boshrelease-concoursetest"
aws-access-key: ~
aws-secret-key: ~

bosh-lite-username: "admin"
bosh-lite-password: "admin"
